org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

group = fi.dy.masa
mod_id = litematica
mod_name = Litematica
author = masa
mod_file_name = litematica-fabric

# Current mod version
mod_version = 0.28.99-dev

# Required malilib version (26.3 final)
malilib_version = 20f798833ad29896880adb232c876111b936c61e

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 26.3
minecraft_version = 26.3

fabric_loader_version = 0.19.5
mod_menu_version = 21.0.0-beta.1
fabric_api_version = 0.161.0+26.3

#iris_version = 1.11.1
#iris_mc_version = 26.2
conditionalmixin_version = 0.6.4
